# Generated by Django 4.0 on 2021-12-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='new_icon')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='icon_created')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='new_image')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='photo_created')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='new_task')),
                ('text', models.TextField(blank=True, null=True, verbose_name='note')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='task_created')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='list_created')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.icon', verbose_name='icon')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image', verbose_name='image')),
            ],
        ),
    ]
