# Generated by Django 4.0 on 2021-12-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_list_icon_alter_list_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='list',
            name='photo',
        ),
    ]
