# Generated by Django 4.0 on 2021-12-26 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_list_icon_remove_list_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.icon'),
        ),
        migrations.AddField(
            model_name='list',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
