# Generated by Django 4.0 on 2021-12-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, choices=[('Today', 'Bugun'), ('Tomorrow', 'Ertaga'), ('Next_week', 'Keyingi hafta')], null=True),
        ),
    ]
