# Generated by Django 4.0 on 2022-01-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.CharField(blank=True, choices=[('Today', 'Bugun'), ('Tomorrow', 'Ertaga'), ('Next_week', 'Keyingi hafta')], max_length=200, null=True),
        ),
    ]
